################# Metricbeat Pulpo Connector DE Configuration #################

# This file is the configuration file for the metricbeat running inside this
# beanstalk docker instance

#============================  Config Reloading ===============================

metricbeat.config.modules:

  # Glob pattern for configuration reloading
  path: ${path.config}/conf.d/*.yml

  # Period on which files under path should be checked for chagnes
  reload.period: 5s

  # Set to true to enable config reloading
  reload.enabled: false

#==========================  Modules configuration ============================
metricbeat.modules:
#------------------------------- Jolokia Module ------------------------------
    - module: jolokia
      metricsets: ["jmx"]
      enabled: true
      period: 10s
      namespace: "metrics"
      hosts: '${PULPO_METRICBEAT_JOLOKIA_HOSTS}'
      path: "/management/jolokia/?ignoreErrors=true&canonicalNaming=false"
      jmx.mappings:
        - mbean: 'java.lang:type=Runtime'
          attributes:
            - attr: Uptime
              field: uptime
        - mbean: 'java.lang:type=Memory'
          attributes:
            - attr: HeapMemoryUsage
              field: memory.heap_usage
            - attr: NonHeapMemoryUsage
              field: memory.non_heap_usage
        - mbean: 'java.lang:type=OperatingSystem'
          attributes:
            - attr: ProcessCpuLoad
              field: cpu.process_load
            - attr: SystemCpuLoad
              field: cpu.system_load

#------------------------------- Docker Module -------------------------------
    - module: docker
      metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
      hosts: ["unix:///var/run/docker.sock"]
      enabled: true
      period: 10s

#================================ General ======================================

tags: '${PULPO_METRICBEAT_TAGS}'

fields:
  env: '${PULPO_METRICBEAT_ENV}'
  service: '${PULPO_METRICBEAT_SERVICE}'

#================================ Outputs ======================================

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  hosts: '${PULPO_METRICBEAT_ES_HOSTS}'

output.console:
  enabled: false

#================================ Logging ======================================
logging.level: debug

logging.to_files: true

logging.to_syslog: false

logging.files:
  keepfiles: 5