################# Metricbeat Pulpo Connector DE Configuration #################

# This file is the configuration file for the metricbeat running inside this
# beanstalk docker instance

#============================  Config Reloading ===============================

metricbeat.config.modules:

  # Glob pattern for configuration reloading
  path: ${path.config}/conf.d/*.yml

  # Period on which files under path should be checked for chagnes
  reload.period: 10s

  # Set to true to enable config reloading
  reload.enabled: false

#==========================  Modules configuration ============================
metricbeat.modules:
#------------------------------- HTTP Module ------------------------------
    - module: http
      metricsets: ["json"]
      period: 10s
      hosts: '${PULPO_METRICBEAT_JOLOKIA_HOSTS}'
      username: '${PULPO_CONTACT_ENGINE_BASIC_AUTH_USER}'
      password: '${PULPO_CONTACT_ENGINE_BASIC_AUTH_PASSWORD}'
      namespace: "metrics"
      path: "/management/metrics"
      ssl.verification_mode: none

#------------------------------- Docker Module -------------------------------
    - module: docker
      metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
      hosts: ["unix:///var/run/docker.sock"]
      enabled: true
      period: 10s

#================================ General ======================================

tags: '${PULPO_METRICBEAT_TAGS}'

fields:
  env: '${PULPO_METRICBEAT_ENV}'
  service: '${PULPO_METRICBEAT_SERVICE}'

#================================ Outputs ======================================

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  hosts: '${PULPO_METRICBEAT_ES_HOSTS}'

output.console:
  enabled: false

#================================ Logging ======================================
logging.level: debug

logging.to_files: true

logging.files:
  keepfiles: 5