- module: jolokia
  metricsets: ["jmx"]
  enabled: true
  period: 10s
  namespace: "metrics"
  hosts: '${PULPO_CONTACTS_ENGINE_JOLOKIA_HOST}'
  path: "/management/jolokia/?ignoreErrors=true&canonicalNaming=false"
  jmx.mappings:
    - mbean: 'java.lang:type=Runtime'
      attributes:
        - attr: Uptime
          field: uptime
    - mbean: 'java.lang:type=Memory'
      attributes:
        - attr: HeapMemoryUsage
          field: memory.heap_usage
        - attr: NonHeapMemoryUsage
          field: memory.non_heap_usage
    - mbean: 'java.lang:type=OperatingSystem'
      attributes:
        - attr: ProcessCpuLoad
          field: cpu.process_load
        - attr: SystemCpuLoad
          field: cpu.system_load